ccshortener:
  code:
    length: 7
    base-url: https://cc.dev.br/
    free-days: 15

info:
  app:
    name: CCShortener
    title: URL SHORTENER API
    artifactId: ccshortener
    description: URL shortening service
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 17
    host:
      url: fttps://localhost

spring:
  application.name: ccshortener-e2e-h2
  datasource:
    url: jdbc:h2:mem:ccshortener;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.default_schema: ccshortener

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: ccshortener
    baseline-on-migrate: true
    clean-disabled: false

logging.level.org.flywaydb: DEBUG