ccshortener:
  code:
    length: 7
    base-url: https://cc.dev.br/
    free-days: 15

info:
  app:
    name: @project.name@
    title: URL SHORTENER API
    artifactId: @project.artifactId@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@
    host:
      url: ${HOST_URL}

server:
  port: 80
  servlet:
    context-path: /@project.artifactId@
spring:
  application:
    name: @project.name@
  datasource:
    url: ${DATABASE_PGSQL_URL}
    username: ${DATABASE_PGSQL_USERNAME}
    password: ${DATABASE_PGSQL_PASSWORD}
  hikari:
    minimumIdle: 1
    idleTimeout: 10000
    connectionTimeout: 30000
    maximumPoolSize: 20
    maxLifetime: 30000
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: ${DATABASE_DIALECT}
  flyway:
    url: ${DATABASE_PGSQL_URL}
    user: ${FLYWAY_USERNAME}
    password: ${FLYWAY_PASSWORD}
    schemas: ${FLYWAY_SCHEMAS}
    locations: classpath:db/migration

# SPRING DOC - BEGIN
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    configUrl: /ccshortener/v3/api-docs/swagger-config
    disable-swagger-default-url: true
    url: /ccshortener/v3/api-docs
    enabled: true
    path: swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    defaultModelsExpandDepth: -1
# SPRING DOC - END

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator


logging:
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR